# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170721_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='person_id',
            new_name='person',
        ),
    ]
