# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170721_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_id',
            new_name='user',
        ),
    ]
