# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170721_1238'),
        ('login', '0004_auto_20170722_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active_courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
