# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_person_active_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hash_code',
            field=models.CharField(default='', max_length=36),
        ),
    ]
