# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20170909_1356'),
        ('login', '0008_auto_20170907_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='active_courses',
            new_name='person_active_courses',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='birthdate',
            new_name='person_birthdate',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='hash_code',
            new_name='person_hash_code',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='profile_pic',
            new_name='person_profile_pic',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user_type',
            new_name='person_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='series',
        ),
        migrations.AddField(
            model_name='person',
            name='person_series_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_user_series', to='series.Series'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
