# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_thread_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='forum.Forum'),
            preserve_default=False,
        ),
    ]
