# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20170816_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replied_to',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
