# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_forum_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='file',
            field=models.FileField(default='files/users/7.jpeg', upload_to=forum.models.upload_file),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='file',
            field=models.FileField(default='files/users/7.jpeg', upload_to=forum.models.upload_file),
            preserve_default=False,
        ),
    ]
