# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-05 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20170905_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=forum.models.upload_comm_file),
        ),
        migrations.AlterField(
            model_name='thread',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=forum.models.upload_thread_file),
        ),
    ]
