# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20170905_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='slug',
            field=models.CharField(default='123456789012345678901234567890', max_length=36),
            preserve_default=False,
        ),
    ]
