# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_fileuploaded_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploaded',
            old_name='file',
            new_name='file_file_path',
        ),
        migrations.RenameField(
            model_name='fileuploaded',
            old_name='reply',
            new_name='file_reply',
        ),
        migrations.RenameField(
            model_name='fileuploaded',
            old_name='slug',
            new_name='file_slug',
        ),
        migrations.RenameField(
            model_name='fileuploaded',
            old_name='thread',
            new_name='file_thread',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='group',
            new_name='forum_group',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='name',
            new_name='forum_name',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='series',
            new_name='forum_series',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='slug',
            new_name='forum_slug',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='adate',
            new_name='reply_adate',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='reply_author',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='desc',
            new_name='reply_desc',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='replied_to',
            new_name='reply_replied_to',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='slug',
            new_name='reply_slug',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='adate',
            new_name='thread_adate',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='author',
            new_name='thread_author',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='desc',
            new_name='thread_desc',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='forum',
            new_name='thread_forum',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='name',
            new_name='thread_name',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='slug',
            new_name='thread_slug',
        ),
    ]
