# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_page_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
