# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 10:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170721_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
