# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('courses', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('location', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course')),
                ('tutors', models.ManyToManyField(related_name='tutors', to='login.Person')),
                ('users', models.ManyToManyField(related_name='users', to='login.Person')),
            ],
        ),
    ]
