# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_tutors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
    ]
