# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170721_1238'),
        ('groups', '0006_remove_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tutors',
            field=models.ManyToManyField(related_name='tutors', to='login.Tutor'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='users', to='login.Person'),
        ),
    ]
