# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20170831_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='group',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='series.Series'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tutors',
            field=models.ManyToManyField(blank=True, null=True, related_name='tutors', to='login.Tutor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='login.Person'),
        ),
    ]
