# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20170907_1023'),
        ('courses', '0007_auto_20170908_0943'),
        ('login', '0008_auto_20170907_1011'),
        ('groups', '0013_auto_20170831_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='location',
            new_name='group_location',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='slug',
            new_name='group_slug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='series',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tutors',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='group_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_course', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_series', to='series.Series'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_tutors',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_tutors', to='login.Tutor'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_users', to='login.Person'),
        ),
    ]
