# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20170909_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_course', to='courses.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_series', to='series.Series'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_tutors',
            field=models.ManyToManyField(related_name='group_tutors', to='login.Tutor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(related_name='group_users', to='login.Person'),
        ),
    ]
