# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import series.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170830_1417'),
        ('series', '0002_auto_20170819_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesFileUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=series.models.upload_file)),
                ('slug', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=36)),
                ('desc', models.TextField()),
                ('adate', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('adate', models.DateField(auto_now=True)),
                ('slug', models.CharField(max_length=36)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Person')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.CharField(default='8ac2afee73114f4bb35e04fa1ebf8a0f', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesthread',
            name='series',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='seriesreply',
            name='replied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.SeriesThread'),
        ),
        migrations.AddField(
            model_name='seriesfileuploaded',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='series.SeriesReply'),
        ),
        migrations.AddField(
            model_name='seriesfileuploaded',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='series.SeriesThread'),
        ),
    ]
