# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20170907_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesreply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='seriesthread',
            name='author',
        ),
    ]
