# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('path', models.FileField(upload_to=resources.models.file_path)),
                ('doc_type', models.CharField(choices=[('AC', 'Activity'), ('CO', 'Course')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
