# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170721_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Resource',
        ),
    ]
