# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-11 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170721_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
