# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20170814_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='course',
            new_name='resource_course',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='doc_type',
            new_name='resource_doc_type',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='document_path',
            new_name='resource_document_path',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='resource_name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='slug',
            new_name='resource_slug',
        ),
    ]
